FROM myorg/alpine:latest

# Install dependencies
RUN apk add -U ca-certificates curl git nginx python3 py3-pip vim

# Set up the application
WORKDIR /app
COPY . .

# Run the application
CMD ["nginx", "-g", "daemon off;"] 